# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Chapolin Veiculos
# Description of the Site
description: Concessionária de Automóveis
# URL of Image of the Site
site-image: /ChapolinVeiculos/assets/images/carros.png
# Keywords of the Site
site-keywords: Carros, Carros baratos, emprestimo de carros
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://i.imgur.com/pEkOmNQ.png

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: teusrocha.matao@gmail.com
facebook_username: Mateus Rocha 
twitter_username: Mateus_Rocha18
instagram_username: mateu_rocha
linkedin_username: https://www.linkedin.com/in/mateus-rocha-369bb0170/
github_username:  mateus1803
youtube_channel_id: 
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: Mateuzão
# URL for the Image of the Author
author-image: https://i.imgur.com/OWbZ2Ie.png
# 60 Words About the Author
author-about: Olá, meu nome é Mateus e desenvolvi esse site/blog para estudos da faculdade.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/mateus1803

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
